image: Visual Studio 2017

# https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
init:
  - ps: if (Get-ChildItem Env:ENABLE_RDP -ErrorAction SilentlyContinue) {iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))} else {echo RDP not enabled}

build_script:
  - git submodule update --init
  - python boots.py create --group test
  - venv\\Scripts\\black --check --diff .
  - venv\\Scripts\\python -c "import sys; print(sys.version)"
  - venv\\Scripts\\pip freeze --all
  - venv\\Scripts\\genbuildinfo "src\\epcpm\\__build.py"
  - venv\\Scripts\\generateversion --distribution epcpm --out "src\\epcpm\\__version.py"
  - ps: Update-AppveyorBuild -Version "v$(venv\\Scripts\\python -c 'import epcpm; print(epcpm.__version__, end=\"\")') b$Env:APPVEYOR_BUILD_NUMBER"
  - ps: if (Get-ChildItem Env:PHRASE -ErrorAction SilentlyContinue) {$Env:PHRASE | Out-File sub/epyqlib/epyqlib/resources/code -Encoding ascii -NoNewline}
  - venv\\Scripts\\pyinstaller pyinstaller.spec
  - move "dist\epcpm" "EPCPM %APPVEYOR_BUILD_VERSION%"
#  - venv\\Scripts\\python sub\\epyqlib\\deploy_win.py --name epcpm
#  - move ..\\*.exe .
  - 7z a "EPCPM %APPVEYOR_BUILD_VERSION%.zip" "EPCPM %APPVEYOR_BUILD_VERSION%"
  - ps: Get-ChildItem .\*.zip | % { Push-AppveyorArtifact $_.FullName }
  - python boots.py build
  - ps: Get-ChildItem dist\* | % { Push-AppveyorArtifact $_.FullName }

test_script:
  - venv\\Scripts\\pytest epcpm.tests --pyargs

deploy_script:
  - python boots.py publish

artifacts:
  - path: "EPCPM %APPVEYOR_BUILD_VERSION%"

# https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
on_finish:
  - ps: if (Get-ChildItem Env:ENABLE_RDP -ErrorAction SilentlyContinue) {$blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))} else {echo RDP not enabled}
